server:
  port: 8088

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/melodymate;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#        show_sql: true
        format_sql: true
        use_sql_comments: true


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace