server:
  port: 8099

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;MODE=Oracle
    driverClassName: org.h2.Driver
    username: sa

  h2:
    console:
      enabled: true

mybatis:
  mapper-locations: mybatis-mapper/*.xml
  config-locations: mybatis-config/*.xml
  typeAliasesPackage: com.MelodyMateBackend.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace